trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(Build.SourcesDirectory)'
 
- script: |
  displayName: 'No se requieren instalaciones'


- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)/css
    mkdir -p $(Build.ArtifactStagingDirectory)/js
    mkdir -p $(Build.ArtifactStagingDirectory)/html
    cp KDS_Games2/KDS_Games/*.js $(Build.ArtifactStagingDirectory)/js
    cp KDS_Games2/KDS_Games/*.css $(Build.ArtifactStagingDirectory)/css
    cp KDS_Games2/KDS_Games/*.html $(Build.ArtifactStagingDirectory)/html
  displayName: 'Copiar archivos al directorio de artefactos'



- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'