trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      if [ ! -f "package.json" ]; then
        echo "El archivo package.json no se encuentra. Abortando el pipeline."
        exit 1
      fi
    displayName: 'Verificar existencia del archivo JSON'

  # Si el archivo JSON está presente, continuar con los pasos del pipeline
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'  
      Contents: '**'  
      TargetFolder: '$(Build.ArtifactStagingDirectory)'  

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'  
      ArtifactName: 'web-artifacts'  

  # Agrega más pasos según tus necesidades, como desplegar la aplicación, etc.



