# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main  # Nombre de la rama que activará el pipeline
  paths:
    include:
      - '*'  # Incluir todos los archivos en el repositorio

pool:
  vmImage: 'ubuntu-latest'  # Imagen de la máquina virtual para ejecutar los pasos

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

  # Agrega más pasos según tus necesidades, como ejecutar pruebas o desplegar la aplicación
