trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'dist'  # Ruta donde se encuentran los archivos generados después de la construcción
      ArtifactName: 'web-artifacts'  # Nombre del artefacto que se publicará

  # Agrega más pasos según tus necesidades, como ejecutar pruebas, desplegar la aplicación, etc.

