trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/kds_Games2' # Ruta relativa a la carpeta que contiene tus archivos HTML, CSS y JS
    Contents: 'games.html'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/WebApp' # Carpeta de destino para los archivos copiados

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/WebApp'
    ArtifactName: 'webapp'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/WebApp'
    artifact: 'webapp'
