trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'  # Carpeta donde se encuentran los archivos de tu proyecto
      Contents: '**'  # Copiar todos los archivos
      TargetFolder: '$(Build.ArtifactStagingDirectory)'  # Carpeta de destino para los archivos de salida

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Ruta donde se encuentran los archivos de salida
      ArtifactName: 'web-artifacts'  # Nombre del artefacto que se publicará

  # Agrega más pasos según tus necesidades, como desplegar la aplicación, etc.


