trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      if [ ! -f "package.json" ]; then
        echo "El archivo package.json no se encuentra. Abortando el pipeline."
        exit 1
      fi
    displayName: 'Verificar existencia del archivo JSON'

  # Si el archivo JSON está presente, continuar con los pasos del pipeline
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'  
      Contents: '**'  
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  # Agrega una tarea para comprimir los archivos en un archivo zip
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/web-artifacts.zip'
      replaceExistingArchive: true

  # Publica el archivo zip como un artefacto del pipeline
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'web-artifacts'
